import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'CAIR',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`antialiased`} suppressHydrationWarning>
        <div
          className={'text-container'}
          style={{ position: 'relative', zIndex: 1 }}
        >
          {children}
        </div>
        <div className='gradient-bg'>
          <svg xmlns='http://www.w3.org/2000/svg'>
            <defs>
              <filter id='goo'>
                <feGaussianBlur
                  in='SourceGraphic'
                  stdDeviation='10'
                  result='blur'
                />
                <feColorMatrix
                  in='blur'
                  mode='matrix'
                  values='1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -8'
                  result='goo'
                />
                <feBlend in='SourceGraphic' in2='goo' />
              </filter>
            </defs>
          </svg>
          <div className='gradients-container'>
            <div className='g1'></div>
            <div className='g2'></div>
            <div className='g3'></div>
            <div className='interactive'></div>
          </div>
        </div>
      </body>
    </html>
  );
}
